services:
  grafana:
    image: grafana/grafana:13.0.1
    container_name: asyncq-demo-grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_LOG_LEVEL: info
      ASYNCQ_DEMO_TEMPLATE_DIR: /var/lib/grafana/asyncq/templates
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: asyncq-kdbbackend-datasource,asyncq-masterdata-panel,asyncq-excel-report-panel
      GF_PLUGINS_PREINSTALL: volkovlabs-table-panel@3.6.5,volkovlabs-echarts-panel@7.2.5,volkovlabs-form-panel@6.3.4
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_USERS_DEFAULT_THEME: light
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../dist:/var/lib/grafana/plugins/asyncq-kdbbackend-datasource:ro
      - ../dist-panel/asyncq-masterdata-panel:/var/lib/grafana/plugins/asyncq-masterdata-panel:ro
      - ../dist-panel/asyncq-excel-report-panel:/var/lib/grafana/plugins/asyncq-excel-report-panel:ro
      - ./templates:/var/lib/grafana/asyncq/templates:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
